# Project: Churn Modelling
#### author: Nabajyoti Majumdar
## Course : Machine Learning A-Z™: Hands-On Python & R In Data Science (Udemy)

### Importing important libraries

In [1]:
import pandas as p
import numpy as n
import matplotlib.pyplot as pl

In [3]:
#loading Dataset
dataset = p.read_csv('CM.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 3].values

### dataset.head() gives us the overview of the dataset

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

#### We have taken the columns from CreditScore to Estimated Salary as our feature set while the variable 'Exited' is the target variable

### Encoding categorical data

In [6]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelenco_X_1 = LabelEncoder()


In [7]:
X[:, 1] = labelenco_X_1.fit_transform(X[:, 1])


In [8]:
labelencoder_X2 = LabelEncoder()

In [9]:
X[:, 2] = labelencoder_X2.fit_transform(X[:, 2])

In [10]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
from sklearn.compose import ColumnTransformer 
onehotencoder = OneHotEncoder()
columnTransformer = ColumnTransformer([('onehotencoder', 
                                        OneHotEncoder(), 
                                        [1])], 
                                      remainder='passthrough')


In [18]:
X= n.array(columnTransformer.fit_transform(X), dtype = n.str) 

In [19]:
X

array([['1.0', '0.0', '0.0', ..., '1', '1', '101348.88'],
       ['0.0', '0.0', '1.0', ..., '0', '1', '112542.58'],
       ['1.0', '0.0', '0.0', ..., '1', '0', '113931.57'],
       ...,
       ['1.0', '0.0', '0.0', ..., '0', '1', '42085.58'],
       ['0.0', '1.0', '0.0', ..., '1', '0', '92888.52'],
       ['1.0', '0.0', '0.0', ..., '1', '0', '38190.78']], dtype='<U9')

In [20]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 1)

In [22]:

# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
clas = XGBClassifier()
clas.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [24]:
y_pred = clas.predict(X_test)

In [25]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [29]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = clas, X = X_train, y = y_train, cv = 2)

E:\Conda_installed\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  % (min_groups, self.n_splits)), UserWarning)


KeyboardInterrupt: 

In [30]:
cm

array([[  3,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   2,   0,   0],
       [  0,   0,   0, ...,   1,   2,   0],
       [  0,   0,   0, ...,   0,   0, 104]], dtype=int64)

In [31]:
y_pred


array([550, 680, 531, ..., 766, 692, 678], dtype=int64)

In [32]:
y_test

array([550, 680, 531, ..., 766, 692, 678], dtype=int64)